export const estados = [
    { id: 1, value: "AC", nome: "Acre" },
    { id: 2, value: "AL", nome: "Alagoas" },
    { id: 3, value: "AP", nome: "Amapá" },
    { id: 4, value: "AM", nome: "Amazonas" },
    { id: 5, value: "BA", nome: "Bahia" },
    { id: 6, value: "CE", nome: "Ceará" },
    { id: 7, value: "DF", nome: "Distrito Federal" },
    { id: 8, value: "ES", nome: "Espírito Santo" },
    { id: 9, value: "GO", nome: "Goiás" },
    { id: 10, value: "MA", nome: "Maranhão" },
    { id: 11, value: "MT", nome: "Mato Grosso" },
    { id: 12, value: "MS", nome: "Mato Grosso do Sul" },
    { id: 13, value: "MG", nome: "Minas Gerais" },
    { id: 14, value: "PA", nome: "Pará" },
    { id: 15, value: "PB", nome: "Paraíba" },
    { id: 16, value: "PR", nome: "Paraná" },
    { id: 17, value: "PE", nome: "Pernambuco" },
    { id: 18, value: "PI", nome: "Piauí" },
    { id: 19, value: "RJ", nome: "Rio de Janeiro" },
    { id: 20, value: "RN", nome: "Rio Grande do Norte" },
    { id: 21, value: "RS", nome: "Rio Grande do Sul" },
    { id: 22, value: "RO", nome: "Rondônia" },
    { id: 23, value: "RR", nome: "Roraima" },
    { id: 24, value: "SC", nome: "Santa Catarina" },
    { id: 25, value: "SP", nome: "São Paulo" },
    { id: 26, value: "SE", nome: "Sergipe" },
    { id: 27, value: "TO", nome: "Tocantins" }
  ];
  